### PR TITLE
Release Version 7.0.0

### PR DESCRIPTION
**Pull request by eeberhard**
## Description

- #114 

It's release time! 🚂 

This is a big one. It took me a while to write the release notes, and in the end I decided to keep the full changelog in at the bottom instead of trying to split everything up by section.

## Review guidelines

Estimated Time of Review: 20 minutes

Please go through the changelog entries and identify any breaking or otherwise significant changes that haven't already been noted.

### CODE REVIEW

**Review by domire8 — APPROVED** [review]
Wohooo what a release! Great effort from all of us!

Thanks again for the many lines that you've written. I think the CHANGELOG is good, I also compared it to the PRs on dynamic components that were necessary due to the breaking changes and I think you have everything there.

**Comment by domire8** [comment]
I'm sorry this has to wait, we still have problems with quaternions

**Review by domire8 — APPROVED** [review]
Let's do it!

**Review by buschbapti — APPROVED** [review]

**Comment by eeberhard** [comment]
Alright, here we gooo 🚂 🔥

**Pull request merged**
