### PR TITLE
Add joint command message to protocol

### PR DESCRIPTION
**Pull request by domire8**
## Description

- aica-technology/network-interfaces#23

This PR adds a JointCommandMessage definition to the protocol and the corresponding encode and decode helpers in clproto. I think this is the simplest solution to the "lightweight interface" problem, where we just want to send simple joint states and joint commands over the wire.

## Review guidelines

Estimated Time of Review: 10 minutes

### CODE REVIEW

**Comment by eeberhard** [comment]
This is a good migration / simplification of the JointCommandMessage that we originally had in network interfaces. But now I've been thinking, we are probably overcomplicating it.

The old StateMessage was originally created for the frank panda LWI and contained a number of fields (JointState, CartesianState, Jacobian, mass matrix). The command message has always been much simpler (JointState and control type). It made sense at the time that the two message types were both structs.

If the command message is just a JointState bundled with a JointStateVariable to define the underlying control type, then I guess it could just as well be an EncodedState (clproto StateMessage) from which you read the message type / StateType to get the control type.

That solution wouldn't require any changes, and also avoids that awkward issue of `JointStateVariable::ALL` which does not neatly map to a control type. 

If we want LWI command messages to be a dedicated message type (for "safety" and avoid confusion between state and command messages), then we could also define the joint command message as:
```protobuf
message JointCommandMessage {
  oneof message_type {
    JointPositions joint_positions = 1;
    JointVelocities joint_velocities = 2;
    JointAccelerations joint_accelerations = 3;
    JointTorques joint_torques = 4;
  }
}
```

Maybe you had already thought / discussed about that (I remember you mentioned using the `oneof` keyword in the message definition. But seeing it now makes it clear to me that bundling JointStateVariable into a message isn't the best option.

**Comment by domire8** [comment]
Okay, fair point. Would you agree that if we don't anything at all and just use EncodedState, this would result in:
1. in the hardware interface: Switch case on the control type on write, if its position -> encode and send as JointPositions, etc.
2. in the drivers, lwis: Receive command, switch case on the message type of the received message and then apply or handle command accordingly?

**Comment by domire8** [comment]
Okay small problem here, the control type is a vector in the robot interface. If we just use joint state classes as command message, we won't be able to transmit that kind of information and we restrict ourselves in the generic lwi interfaces.

**Comment by eeberhard** [comment]
> Okay, fair point. Would you agree that if we don't anything at all and just use EncodedState, this would result in:
> 
> 1. in the hardware interface: Switch case on the control type on write, if its position -> encode and send as JointPositions, etc.
> 2. in the drivers, lwis: Receive command, switch case on the message type of the received message and then apply or handle command accordingly?

Yes to both (this only applies to the LWI hardware interface in any case).

>the control type is a vector in the robot interface. If we just use joint state classes as command message, we won't be able to transmit that kind of information and we restrict ourselves in the generic lwi interfaces.

Also yes but this is nothing new. Both in the original CommandMessage and in your first proposal, we assume (expect) a consistent control type. The ability to command different joints on different control types is a feature of ros2_control but not one that we would realistically use in normal use-cases. It might apply to a complex system (for example, a dual-arm setup which has one position-controlled arm and one torque-controlled arm), but we would generally want to represent them as two systems if possible.

Mainly, the LWI is intended to be just that: lightweight. A simple protocol to send command and receive state which can be re-used across hardware and simulator servers.

**Comment by domire8** [comment]
Alright, then I will close this here without merging :+1:

**Pull request closed without merging**
