### PR TITLE
Fix angular stiffness calculation in impedance controller

### PR DESCRIPTION
**Pull request by eeberhard**
* Conjugate the angular difference if the real part is negative to ensure that the resultant torque is always applied in the right direction

* Add test to verify that the command torque is always parallel to the equivalent quaternion derivative for any random orientation

## Description

- #116 

This PR solves the issue by flipping the quaternion difference if the real part is negative, thereby making sure the torque is always applied in the right direction.

We know the point attractor works, so I started first by comparing the result of `ds->evaluate()` from the PointAttractor, then simplified it to just the log part (otherwise we would have to link `dynamical_systems` in the controller tests). The fix essentially just repeats the logic in the `log` operation.

Recall that we don't take the log in the impedance controller because we are not actually trying to map a derivative (angular velocity) but instead just acting purely and proportionally on an angular displacement vector. 

## Review guidelines

Estimated Time of Review: 5 minutes

## Checklist before merging:
- [ ] Test it on the robot (Monday)

### Blocks:
- #115

### CODE REVIEW

**Review by domire8 — COMMENTED** [review]
I will gladly test that Monday !

**Review by buschbapti — COMMENTED** [review]
Good catch and simple fix in the end. Does that also work in cases where `w=0`? I recall I had a problem in this edge case as you can't distinguish between the two hemispheres then but maybe that is sufficient here and also I am not so sure anymore, this was too long ago.

**Comment by eeberhard** [comment]
> Good catch and simple fix in the end. Does that also work in cases where `w=0`? I recall I had a problem in this edge case as you can't distinguish between the two hemispheres then but maybe that is sufficient here and also I am not so sure anymore, this was too long ago.

Thanks for thinking about it. The case of $w=0$ is kind of a singularity from a controls perspective, because it represents 180º. If the orientation is diametrically opposed from the target, there is not really a "correct" direction to rotate; any direction would bring us towards the target. The problem we were seeing was instead caused when $w$ was close to 1 and flipped to -1 (i.e. when the orientation moved near and over the target). Additionally, we don't need any checks for $w$ near 0 because we aren't doing any normalization or division by the real part.

**Review by buschbapti — APPROVED** [review]
Thanks for the explanation. Makes sense. Looking forward to the test on the robot then.

**Review by domire8 — APPROVED** [review]
Alright, this works! Let's get it in :) Thanks

**Pull request merged**
