### PR TITLE
Remove set_filled and make set_empty protected

### PR DESCRIPTION
**Pull request by domire8**
Review by commit.
For me there is no reason anymore to have `set_filled` because we don't want to reset the timestamp in there. Therefore, one can just use the `set_empty` method with a boolean input to modify the empty attribute. Additionally, the `set_empty` should be protected because we don't want a user to manipulate that attribute at will.

### CODE REVIEW

**Comment by buschbapti** [comment]
Something else is happening in here that have more consequences that what the description provides. The change in clprotto goes much beyond and should be a separate PR imo. Also because I am not entirely sure about the consequences as I don't remember if in modulo we changed to not publish empty states.

Regarding the set_filled removal, it is also a matter of style. You could decide to do two setters instead of one (`set_filled` and `set_empty`) as this is binary. For booleans I kind of like that. Similarly, you could have two getters (`is_filled` and `is_empty`) to avoid always doing `!is_empty` that is the common use case. I don't mind sticking to only one though. Making it protected is good though.

**Comment by domire8** [comment]
> Regarding the set_filled removal, it is also a matter of style. You could decide to do two setters instead of one (`set_filled` and `set_empty`) as this is binary.
I will try to explain my motivation. The status quo is: We have a `set_filled` and a `set_emtpy` but the latter takes a boolean argument. That for me is a big inconsitency and makes `set_filled` useless. So the two solutions that I see are:
1. `set_filled` and `set_emtpy` but both have no argument
2. only `set_empty` but with argument

Now even though it is nice to have option one with two simple setter, they will make some operations like `swap` harder because in there it's very nice to just to: `state1.set_empty(state2.is_empty())`. That's why I like to have option 2. Anyway now that it's not public anymore, we don't expect common users to use either of those function, and we can expect super users to use the `set_empty` with arguemnt instead of `set filled`. 


> Similarly, you could have two getters (`is_filled` and `is_empty`) to avoid always doing `!is_empty` that is the common use case.

You should definitely not do `!is_empty` anymore because we have the boolean operator. So its either:
- `if (state)`
- `if (state.is_empty()`

**Comment by domire8** [comment]
> Something else is happening in here that have more consequences that what the description provides. The change in clprotto goes much beyond and should be a separate PR imo. Also because I am not entirely sure about the consequences as I don't remember if in modulo we changed to not publish empty states.

Ok fair point that it should maybe be split. But then I have to do clproto before making `set_empty` protected. Anyway let's talk about it here. I do think that this change is reasonable and should not have amything to do with modulo (we did decide to NOT publish empty states there though). I assume you initially had your reasons to be able to change from empty to filled state but in the past 2 years I did not come across where we would have done that and it would have made sense to send a state over the network that is tagged empty but contains data. I think an empty state is empty and should not have any data, hence we dont have to send all the fields in clproto.

**Comment by domire8** [comment]
Pause this PR until we close #7

**Comment by domire8** [comment]
Closing in favor of #7, #9 and #14

**Pull request closed without merging**
