### PR TITLE
Release Version 8.0.0

### PR DESCRIPTION
**Pull request by domire8**
## Description

Release time!

@eeberhard if you want to make changes to the Contributing, Readme, etc, feel free to do this here.

The commits between version 7.2.0 and 7.3.0 show up because I made a mistake in the 7.3.0 release I think (squash and  merge instead of merge commit or similar...)

## Review guidelines

Estimated Time of Review: 10 minutes

## Checklist before merging:

- [x] Confirm that the relevant changelog(s) are up-to-date in case of any user-facing changes

### CODE REVIEW

**Review by bpapaspyros — DISMISSED** [review]
Looks great !

**Review by yrh012 — APPROVED** [review]
Amazing!

**Review by eeberhard — DISMISSED** [review]
# 🚂 🔥 

Changelogs and readmes look great, thanks for the work to rewrite those alongside all of the other refactor work here.

Since we are closing `develop` branch now, you could also have made this release PR (which updates changelogs and versions) on develop, and then merge develop into main to officially close it. But I suppose since we are deleting develop anyway then it doesn't matter if it ends up being one commit behind!

So, LGTM, you can ship it 👍

**Review by bpapaspyros — DISMISSED** [review]

**Comment by domire8** [comment]
@LouisBrunner Will your changes to the build system (dependency management) potentially require a new major version for control libraries? If that's the case I wonder if this should wait even a bit more

**Comment by LouisBrunner** [comment]
> @LouisBrunner Will your changes to the build system (dependency management) potentially require a new major version for control libraries? If that's the case I wonder if this PR should wait even a bit more

Potentially. We haven't touched on that yet. I don't know if we want all the packages to be bumped one major version or if we are happy with a minor bump. Technically, it doesn't break the existing package so I would argue a minor bump would be enough.

**Review by eeberhard — APPROVED** [review]
🚂 🔥 

Thanks for taking your time with this release to consider the downstream impact. As far as I can tell, v8 is good to go now!

**Review by bpapaspyros — APPROVED** [review]

**Pull request merged**
