### PR TITLE
Fix inverse operation in CartesianState

### LINKED ISSUE #30: Fix transform operation in CartesianState
The transformation operator `*` should correctly respect acceleration and wrench. For starting reference, see this excellent PR draft: https://github.com/epfl-lasa/control-libraries/pull/164

### PR DESCRIPTION
**Pull request by eeberhard**
## Description

- #29 

After a lot of head scratching and right-hand-ruling, I was able to understand how our representation of twist and accelerations behave in the inverse case. I added a lot of specific test cases for how the various components of state interact and I think it's now in a correct state for twist and acceleration.

This issue was not the highest priority but I felt inspired to do it on my Wednesday hack day as part of the release 7.0 milestone. I was additionally motivated to better understand our transforms so that I can finally resolve #30 afterwards.

## Supporting information
I did look at various references but in the end worked most things out again on first principles. After verifying the forward transform of twist and acceleration was correct, I was also able to deconstruct that to understand and test the inverse.

This is probably the most succinct summary I could find.
https://en.wikipedia.org/wiki/Rotating_reference_frame

Also, I started using CLion [task and time tracking](https://www.jetbrains.com/help/clion/managing-tasks-and-context.html), which is quite useful. I might give a quick presentation on it next week. It tells me I spent was 6 and a half hours on this problem. Most of it was trying to think of reasonable test cases and mentally checking frames of reference.

## Review guidelines

Estimated Time of Review: 30-60 minutes

Most of the diff is from the new tests. I hope they are clear by the comments and provide sufficient support for the changes.

### CODE REVIEW

**Comment by eeberhard** [comment]
As more supporting information, here is a super detailed and a highly accurate schematic I developed while thinking 😄 

Image 25 01 23 at 18 52

**Comment by buschbapti** [comment]
This is wonderful. I am glad you worked that out and that the test prove that it is working as it should. It was a technical debt that was bothering me for a while. Not sure if we will go in that direction soon but it should enable us to use second order dynamical systems efficiently.

**Comment by eeberhard** [comment]
To help understand why the inverse includes these cross product terms and is not just a negation / rotation of the state variables, consider the following.

Firstly, we express all of our state variables from the perspective of the reference frame, but applied to the frame itself. In other words, all of the directions are relative to the "world" frame (e.g. position in world X, velocity around world Y), but the actual twist / acceleration / wrench is applied at the frame. Think of a frame in rviz - if we give it a twist, it should spin around itself, even if it is offset from the reference frame. 

We can also call the "reference frame and frame" the "static and body frames" respectively. When body B with position offset and some angular velocity is expressed in a static frame A, then the inverse is the “static” frame A seen from the body B perspective. Because B was rotating about its own axis, frame A now appears to be moving with linear velocity radially based on the distance offset (as well as rotating in the opposite direction). The same goes for angular acceleration - the inverse causing apparent motions due to coriolis and centrifugal effects.

**Review by buschbapti — DISMISSED** [review]
Thanks for the explanation I don't see any problems and the test clearly shows that it work. Super good work.

**Review by domire8 — CHANGES_REQUESTED** [review]
Super cool, thanks for doing this. The test cases are exhaustive and make sense to me. :rocket: 

Please update the version and changelog

**Review by domire8 — APPROVED** [review]

**Pull request merged**
