### PR TITLE
release: patch v7.4.1 with docker image metadata

### PR DESCRIPTION
**Pull request by eeberhard**
## Description

In #188, metadata was added to the control libraries docker image to support the new aica-technology/package-builder:v1. This came in as part of the v8 release with other breaking changes. However, some downstream users (aica-technology/modulo) are not yet ready to upgrade to v8 but would still benefit from the docker image metadata. In particular, https://github.com/aica-technology/modulo/pull/92 is blocked.

I would like to retroactively make a patch release v7.4.1 which simply adds the docker image metadata on top of the existing v7.4.0 tag. I would merge this onto the patch/v7.4.1 branch, which currently targets the existing v7.4.0 release tag, and then make a new tag on that updated branch to trigger the CI to build the corresponding image. 

## Review guidelines

Estimated Time of Review: 2 minutes

## Checklist before merging:

- [x] Confirm that the relevant changelog(s) are up-to-date in case of any user-facing changes

### CODE REVIEW

**Comment by domire8** [comment]
How is that going to work with all our CIs? What will happen to the patch/v7.4.1 branch afterwards?

**Comment by LouisBrunner** [comment]
> How is that going to work with all our CIs? What will happen to the patch/v7.4.1 branch afterwards?

We could add a workflow so that `patch/vX.Y.Z` are automatically published like a `main` release. But it's pretty common to have alternative `main` branches to do backports for older versions.

**Comment by domire8** [comment]
> I was planning to tag the commit on the branch as v7.4.1 after merging and then delete the branch.

The CI now detects changes of the VERSION file on push to main, there is no workflow on tag anymore.

**Comment by eeberhard** [comment]
> The CI now detects changes of the VERSION file on push to main, there is no workflow on tag anymore.

oops, of course I was looking at the old CI from v7.4.0. Then I guess we could change the CI in this PR to do what we want on push to patch/v7.4.1

**Review by domire8 — APPROVED** [review]
I think this seems okay, might just be worth checking if the `v7.4.1` is a correct argument to the two actions

**Pull request merged**
